Fix a bug preventing the CLI from runnning
Whenever one would use the synergy CLI, for example:
`synergy --help`
it would fail with:
`ERROR: cannot import name Execute`

In this commit we fix the issue by correcting the typo,
referencing `ExecuteCommand` instead of `Execute` from the
synergy-service package.

Change-Id: I1ddc6d209b9d7b899f9be2f54df368401e351ff2